### ISSUE TITLE
Unknown/unsupported OpenSSL version ("30100040 (OpenSSL 3.1.4 24 Oct 2023)")

### ISSUE THREAD

**Issue by ickc** [gridcf/gct#219] opened 2023-11-14 17:04 UTC
When installing on Arch Linux,

```sh
checking OpenSSL library version... configure: error: Unknown/unsupported OpenSSL version ("30100040 (OpenSSL 3.1.4 24 Oct 2023)")
```

From https://github.com/gridcf/gct/blob/07008c37abe56bafba82fe052b0f2cd11358ee88/gsi_openssh/source/configure.ac#L2844-L2862

C.f. https://aur.archlinux.org/packages/gct#comment-943688

**Comment by fscheiner** [comment] 2023-11-14 21:40
Thanks for the pointer.

But I wonder why it doesn't work for your OpenSSL version 3.1.4. Because considering that https://github.com/openssh/openssh-portable/commit/f6d3ed9a8a9280cbb68d6a499850cfe810e92bd0 enables version 3.2.x and https://github.com/openssh/openssh-portable/commit/3e21d58a09894acb38dc69ed615d101131f473d0 enables 3.3.x, 301 should enable 3.1.x if I'm not mistaken.

And `301*` should at least match the first part of `30100040 (OpenSSL 3.1.4 24 Oct 2023)`.

**Comment by msalle** [comment] 2023-11-22 17:59
but the [commit](https://github.com/gridcf/gct/commit/f60262da4d171415c8482cdaeec4025a61ce8cab#diff-318099beed62376de965ed08f01fde64f28a646ae64c749f1e2b40d97aa37a7fL2829) adds just the 300 and 301 as *unsupported* versions. Also the one before, from 2 years ago, adds 300 as *unsupported* version.
That's different from this [commit](https://github.com/openssh/openssh-portable/commit/f6d3ed9a8a9280cbb68d6a499850cfe810e92bd0#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810L2815-L2821) in the upstream patches.

**Comment by fscheiner** [comment] 2023-11-22 18:10
@msalle 
> but the [commit](https://github.com/gridcf/gct/commit/f60262da4d171415c8482cdaeec4025a61ce8cab#diff-318099beed62376de965ed08f01fde64f28a646ae64c749f1e2b40d97aa37a7fL2829) adds just the 300 and 301 as _unsupported_ versions. Also the one before, from 2 years ago, adds 300 as unsupported version.

No, I think there is no fall-through to the unusupported `*)` case. If there was, all cases would fall-through instead of ending at the `;;`.

**Comment by msalle** [comment] 2023-11-23 17:49
ah right indeed, sorry shouldn't have looked on my phone.

The problem is that the configure.ac in gct-6.2.1653033972/gsi_openssh/source is an old one. I just noticed that the configure and configure.ac in there only support up to 3.0.X.
Also the current draft release still points to that version of Jun 8, 2022. The 301 support dates back to Feb 21 (see https://github.com/gridcf/gct/commit/f60262da4d171415c8482cdaeec4025a61ce8cab)

**Comment by fscheiner** [comment] 2023-11-23 18:55
> ah right indeed, sorry shouldn't have looked on my phone.

I made the same error at first, because it just looks like so.

> The problem is that the configure.ac in gct-6.2.1653033972/gsi_openssh/source is an old one. I just noticed that the configure and configure.ac in there only support up to 3.0.X. 

Now I understand the problem. I didn't notice that issue as the OP quoted from current code state - where it looks and is OK IIUC - but used the last release tarball when trying to build the package on AUR, which is pre 2022-05-24.

> Also the current draft release still points to that version of Jun 8, 2022. The 301 support dates back to Feb 21 (see [f60262d](https://github.com/gridcf/gct/commit/f60262da4d171415c8482cdaeec4025a61ce8cab))

Yes, I haven't yet updated the draft release since copying the content from the last release.

**Comment by fscheiner** [comment] 2023-11-23 18:56
@ickc: This issue will hence be solved with the next GCT release that will materialize before end of this year.

**Comment by ickc** [comment] 2023-11-24 16:04
Thanks all. I guess it should be closed now.

**Comment by fscheiner** [comment] 2023-11-24 16:10
Oh, we usually keep issues open until there's a release that fixes them.

**Comment by ickc** [comment] 2023-11-24 16:25
Ok, sure. Thanks again! Sorry for not having time to look into it again and providing more details, but you all figured it out already.

**Comment by msalle** [comment] 2024-12-25 14:40
I think this issue can be closed, I think the fix for this has been released. I'll open a new issue for support for 3.4 though.

**Closed by msalle** 2024-12-25 14:40 UTC
Labels: fixed in git master
