### ISSUE TITLE
Issue with log trasfer file GCT 6.2

### ISSUE THREAD

**Issue by fcola000** [gridcf/gct#130] opened 2020-07-13 16:43 UTC
Dear support,

in our cluster we are using version 6.2 of GCT. Even if we have configured both the "log_single" and "log_transfer" files, and, the "log_level" is ALL, when a transfer is performed, the log_transfer file remains empty.
Could you please help us to solve this issue?
Do you need other info?

Best regards,

Francesco

**Comment by fscheiner** [comment] 2020-07-23 12:27
Dear Francesco,

I moved that issue to the gridcf/gct repo, as the GCT documentation is correct, but the GCT source had lost that ability in the meantime. I assume this is a duplicate of #110, which is _fixed in git master_ since a while. But there was no new release of the GCT made since then, so it's not yet in the RPM packages from EPEL/Fedora.

Until a new release of the GCT is made, you can also create updated RPM packages yourself manually and use these for now. I've described the process in [this comment](https://github.com/gridcf/gct/issues/110#issuecomment-585666603).

I'll close that ticket now and mark it as duplicate. Please reopen if your problem persists or if I was wrong with my assumption.

Cheers,
Frank

**Comment by fscheiner** [comment] 2020-07-23 12:28
Duplicate of #110.

**Closed by fscheiner** 2020-07-23 12:28 UTC
Labels: duplicate
